-- Fix schema drift by ensuring all recently added columns exist
ALTER TABLE IF EXISTS "Service"
    ADD COLUMN IF NOT EXISTS "avgActualDurationMins" INTEGER,
    ADD COLUMN IF NOT EXISTS "allowAppointments" BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS "requireManualCheckIn" BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS "appointmentGranularityMins" INTEGER NOT NULL DEFAULT 15,
    ADD COLUMN IF NOT EXISTS "concurrentSlots" INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS "minDuration" INTEGER,
    ADD COLUMN IF NOT EXISTS "maxDuration" INTEGER,
    ADD COLUMN IF NOT EXISTS "bufferDuration" INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "formConfig" JSONB;

ALTER TABLE IF EXISTS "Visit"
    ADD COLUMN IF NOT EXISTS "queueId" TEXT,
    ADD COLUMN IF NOT EXISTS "estimatedWaitMins" INTEGER,
    ADD COLUMN IF NOT EXISTS "actualWaitMins" INTEGER,
    ADD COLUMN IF NOT EXISTS "checkInCode" TEXT,
    ADD COLUMN IF NOT EXISTS "appointmentId" TEXT,
    ADD COLUMN IF NOT EXISTS "assignedStaffId" TEXT,
    ADD COLUMN IF NOT EXISTS "assignedResourceId" TEXT;

ALTER TABLE IF EXISTS "Queue"
    ADD COLUMN IF NOT EXISTS "isPaused" BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS "rules" JSONB;

ALTER TABLE IF EXISTS "Appointment"
    ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'PENDING_APPROVAL',
    ADD COLUMN IF NOT EXISTS "cancellationReason" TEXT,
    ADD COLUMN IF NOT EXISTS "staffId" TEXT,
    ADD COLUMN IF NOT EXISTS "resourceId" TEXT;
