services:
  - type: web
    name: qmova-evolution-api
    runtime: image
    image:
      url: evoapicloud/evolution-api:v2.3.7
    envVars:
      - key: SERVER_PORT
        value: 8080
      - key: AUTHENTICATION_TYPE
        value: apikey
      - key: AUTHENTICATION_API_KEY
        value: "<EVOLUTION_API_KEY>"
