import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { QRCodeSVG } from 'qrcode.react';
import { io, Socket } from 'socket.io-client';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Logo } from '../../components/Logo';

interface VisitState {
  id: string;
  queueId: string;
  displayId: string;
  accessToken: string;
  currentState: 'CREATED' | 'WAITING' | 'CHECKED_IN' | 'IN_SERVICE' | 'COMPLETED' | 'MISSED';
  waitingStart: string;
  createdAt: string;
  customer: { name: string };
  service: { name: string; expectedDuration: number };
  location: { name: string; address: string };
  tenant: { name: string };
  position?: number;
  ewt?: number;
}

export default function CustomerTicketScreen() {
  const router = useRouter();
  const { accessToken } = router.query;
  const queryClient = useQueryClient();

  // 1. Server-authoritative fetch using React Query
  const { data: visit, isLoading, isError, refetch } = useQuery<VisitState>({
    queryKey: ['public-visit', accessToken],
    queryFn: async () => {
      const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3000'}/public-visit/${accessToken}`);
      if (!res.ok) throw new Error('Failed to fetch visit');
      return res.json();
    },
    enabled: !!accessToken,
    refetchOnWindowFocus: true, // Auto refetch when user returns to tab
  });

  // 2. WebSocket reconciliation
  useEffect(() => {
    if (!visit || !visit.queueId) return;

    const socket: Socket = io(process.env.NEXT_PUBLIC_WS_URL || 'http://localhost:3000', {
      transports: ['websocket'],
    });

    socket.on('connect', () => {
      // Re-fetch data to ensure we didn't miss anything while disconnected
      refetch();
      socket.emit('subscribeToVisit', visit.id);
    });

    // Handle incoming events generated by OutboxProcessor
    socket.on('VISIT_CALLED', (payload) => {
      if (payload.visitId === visit.id) {
        queryClient.invalidateQueries({ queryKey: ['public-visit', accessToken] });
      } else {
        // Someone else was called, potentially updating our position/ETA
      }
    });

    socket.on('VISIT_COMPLETED', (payload) => {
      if (payload.visitId === visit.id) {
        queryClient.invalidateQueries({ queryKey: ['public-visit', accessToken] });
      }
    });

    socket.on('VISIT_MISSED', (payload) => {
      if (payload.visitId === visit.id) {
        queryClient.invalidateQueries({ queryKey: ['public-visit', accessToken] });
      }
    });

    socket.on('reconnect', () => {
      refetch();
      socket.emit('subscribeToVisit', visit.id);
    });

    return () => {
      socket.disconnect();
    };
  }, [visit?.id, visit?.queueId, accessToken, queryClient, refetch]);

  if (isLoading) {
    return (
      <div className="bg-surface text-on-surface flex items-center justify-center min-h-screen">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
      </div>
    );
  }

  if (isError || !visit) {
    return (
      <div className="bg-surface text-on-surface flex flex-col items-center justify-center min-h-screen text-center p-4">
        <span className="material-symbols-outlined text-6xl text-rose-500 mb-4">error</span>
        <h1 className="text-2xl font-bold mb-2">Invalid or Expired Ticket</h1>
        <p className="text-zinc-400">This ticket does not exist or has expired.</p>
      </div>
    );
  }

  // --- Rendering States ---

  if (visit.currentState === 'COMPLETED') {
    return (
      <div className="bg-surface text-on-surface flex items-center justify-center min-h-screen p-4 sm:p-8 font-body-md text-body-md antialiased">
        <div className="w-full max-w-md mx-auto bg-zinc-950 min-h-screen sm:min-h-[850px] sm:h-[850px] sm:rounded-[2.5rem] sm:border-[8px] border-zinc-800 relative overflow-hidden shadow-2xl flex flex-col items-center justify-center p-8">
          <div className="w-24 h-24 rounded-full bg-emerald-500/20 text-emerald-500 flex items-center justify-center mb-6">
            <span className="material-symbols-outlined text-5xl">done_all</span>
          </div>
          <h1 className="font-headline-lg text-headline-lg text-zinc-50 mb-2 text-center tracking-tight font-semibold">Service Complete</h1>
          <p className="font-body-md text-body-md text-zinc-400 text-center mb-8">Thank you for visiting {visit.location.name}. Please leave us a review.</p>
          <button className="w-full h-[56px] bg-primary hover:bg-primary-container text-white rounded-2xl font-headline-sm transition-colors">
            Leave Feedback
          </button>
        </div>
      </div>
    );
  }

  if (visit.currentState === 'MISSED') {
    return (
      <div className="bg-surface text-on-surface flex items-center justify-center min-h-screen p-4 sm:p-8 font-body-md text-body-md antialiased">
        <div className="w-full max-w-md mx-auto bg-zinc-950 min-h-screen sm:min-h-[850px] sm:h-[850px] sm:rounded-[2.5rem] sm:border-[8px] border-zinc-800 relative overflow-hidden shadow-2xl flex flex-col items-center justify-center p-8">
          <div className="w-24 h-24 rounded-full bg-rose-500/20 text-rose-500 flex items-center justify-center mb-6">
            <span className="material-symbols-outlined text-5xl">event_busy</span>
          </div>
          <h1 className="font-headline-lg text-headline-lg text-zinc-50 mb-2 text-center tracking-tight font-semibold">Ticket Missed</h1>
          <p className="font-body-md text-body-md text-zinc-400 text-center mb-8">Your ticket was called but you were not present. Please join the queue again.</p>
        </div>
      </div>
    );
  }

  if (visit.currentState === 'IN_SERVICE') {
    return (
      <div className="bg-surface text-on-surface flex items-center justify-center min-h-screen p-4 sm:p-8 font-body-md text-body-md antialiased">
        <div className="w-full max-w-md mx-auto bg-zinc-950 min-h-screen sm:min-h-[850px] sm:h-[850px] sm:rounded-[2.5rem] sm:border-[8px] border-zinc-800 relative overflow-hidden shadow-2xl flex flex-col">
          <div className="flex-1 flex flex-col items-center justify-center p-8 text-center">
            <div className="w-24 h-24 rounded-full bg-sky-500/20 text-sky-400 flex items-center justify-center mb-6 animate-pulse">
               <span className="material-symbols-outlined text-5xl">notifications_active</span>
            </div>
            <h1 className="font-headline-lg text-headline-lg text-zinc-50 mb-2 tracking-tight font-semibold">It's your turn!</h1>
            <p className="font-body-lg text-body-lg text-sky-400 mb-8">Please proceed to the counter</p>
            <div className="bg-white p-6 rounded-2xl shadow-xl">
               <QRCodeSVG value={visit.accessToken} size={200} />
            </div>
            <p className="font-body-sm text-body-sm text-zinc-400 mt-6 max-w-[200px]">Show this QR to the operator at the desk.</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-surface text-on-surface flex items-center justify-center min-h-screen p-4 sm:p-8 font-body-md text-body-md antialiased">
      <Head>
        <title>Your Digital Pass - Qmova</title>
        <style>{`
          .pulse-ring {
            animation: pulse-ring 2s cubic-bezier(0.215, 0.61, 0.355, 1) infinite;
          }
          @keyframes pulse-ring {
            0% { transform: scale(0.8); opacity: 0.5; }
            70%, 100% { transform: scale(2); opacity: 0; }
          }
        `}</style>
      </Head>

      <div className="w-full max-w-md mx-auto min-h-screen sm:min-h-[850px] sm:h-[850px] sm:rounded-[2.5rem] sm:border-[8px] border-zinc-800 relative overflow-hidden shadow-2xl bg-zinc-950 text-zinc-50 flex flex-col">
        
        <header className="fixed sm:absolute top-0 w-full z-50 flex items-center justify-between px-6 h-[72px] bg-zinc-950/80 backdrop-blur-md border-b border-zinc-800/50">
          <div className="flex items-center gap-3">
            <Logo width={120} height={19} forceTheme="dark" />
          </div>
          <button className="text-zinc-400 hover:text-zinc-100 transition-colors w-10 h-10 flex items-center justify-center">
            <span className="material-symbols-outlined">more_vert</span>
          </button>
        </header>

        <main className="flex-1 overflow-y-auto pt-[72px] pb-24 px-4 scroll-smooth">
          <div className="flex flex-col items-center justify-center h-full min-h-[600px] transition-opacity duration-500">
            <div className="w-full max-w-sm bg-white text-zinc-900 rounded-[2rem] p-8 flex flex-col items-center relative overflow-hidden shadow-xl border border-zinc-200 mt-8">
              
              <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-sky-500 to-sky-400"></div>
              
              <div className="relative w-16 h-16 mb-6 flex items-center justify-center">
                <div className="absolute inset-0 rounded-full border-2 border-emerald-500 pulse-ring"></div>
                <div className="w-12 h-12 rounded-full bg-emerald-100 flex items-center justify-center z-10">
                  <span className="material-symbols-outlined text-emerald-600" style={{ fontVariationSettings: "'FILL' 1" }}>schedule</span>
                </div>
              </div>
              
              <h2 className="font-headline-md text-headline-md text-center mb-1 text-zinc-900 tracking-tight font-semibold">
                You are Waiting
              </h2>
              <p className="font-body-sm text-body-sm text-zinc-500 text-center mb-8">Service: {visit.service.name}</p>
              
              {(visit.position !== undefined && visit.position > 0) && (
                <div className="flex gap-4 w-full mb-6">
                  <div className="flex-1 bg-zinc-50 border border-zinc-100 rounded-xl p-4 flex flex-col items-center">
                    <span className="text-zinc-400 text-xs font-bold uppercase tracking-widest mb-1">Position</span>
                    <span className="text-2xl font-bold text-zinc-900">{visit.position}</span>
                  </div>
                  <div className="flex-1 bg-zinc-50 border border-zinc-100 rounded-xl p-4 flex flex-col items-center">
                    <span className="text-zinc-400 text-xs font-bold uppercase tracking-widest mb-1">Est. Wait</span>
                    <span className="text-2xl font-bold text-zinc-900">{visit.ewt}m</span>
                  </div>
                </div>
              )}

              <div className="text-center mb-8 w-full border-y border-zinc-100 py-6">
                <span className="block font-label-caps text-label-caps text-zinc-400 tracking-widest uppercase mb-2">Ticket ID</span>
                <div className="font-data-mono-lg text-data-mono-lg text-zinc-950 tracking-tight text-3xl font-bold">{visit.displayId}</div>
              </div>
              
              <div className="w-[160px] h-[160px] rounded-2xl flex items-center justify-center bg-white mb-8 relative border border-zinc-100 p-2">
                 <QRCodeSVG value={visit.accessToken} size={140} />
              </div>
              
              <p className="font-body-sm text-body-sm text-zinc-400 text-center max-w-[200px]">Present this QR code or ID at the front desk when called.</p>
            </div>
            
            <div className="flex gap-4 mt-8 w-full max-w-sm px-4">
              <button className="flex-1 h-[44px] bg-zinc-900 border border-zinc-800 hover:bg-zinc-800 text-zinc-300 rounded-xl font-body-md text-body-md transition-colors flex items-center justify-center gap-2">
                <span className="material-symbols-outlined text-[18px]">directions_run</span> Running Late
              </button>
              <button className="flex-1 h-[44px] bg-transparent border border-rose-900/50 hover:bg-rose-900/20 text-rose-400 rounded-xl font-body-md text-body-md transition-colors flex items-center justify-center">
                Cancel Visit
              </button>
            </div>
          </div>
        </main>
        
        <div className="absolute bottom-0 left-0 w-full h-12 bg-gradient-to-t from-zinc-950 to-transparent pointer-events-none"></div>
      </div>
    </div>
  );
}
